name: Publish to NPM
on:
  push:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm install && npm run build
      - name: Publish package on NPM 📦
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@svensson84'
        run: npm publish --respository https://registry.npmjs.org --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}